### ISSUE TITLE
Add cell count estimation in feature extraction step

### ISSUE THREAD

**Issue by gwaybio** [WayScience/CFReT_data#13]
In #12 I create a cell count dataframe. We have to do this often, for many different visualizations.

Consider adding a cell count module as a standard step in preprocessing so that we only have to do this once.

**Comment by jenna-tomkinson** [comment]
Agreed, in our other repositories, this is included after the `annotation` step. 

This can be changed in a refactor as I believe we will likely want to move to use CytoTable instead of the `SingleCells` class. 

This will likely be done once a new plate is received.

**Comment by jenna-tomkinson** [comment]
This looks to be old and likely solved, so I will close this issue.
