### ISSUE TITLE
Create platemap visualization for all plates

### ISSUE THREAD

**Issue by gwaybio** [WayScience/CFReT_data#14]
In #12 I only added a platemap for plate 2 (Factinadjusted). We should add a platemap for plate 1 (and all subsequent plates as well!)

**Comment by jenna-tomkinson** [comment]
I believe that all platemaps have been made for all current plates. The code is referenced in the 4th module, but I think it should be added into the download data module instead. 

This will be included a PR in the future, so I am assigning this to myself.

**Comment by jenna-tomkinson** [comment]
I am going to close this since platemap visualizations have been created and fit well in the `./metadata` module.
