### ISSUE TITLE
Mint DOI

### ISSUE THREAD

**Issue by gwaybio** [WayScience/CFReT_data#46]
We need to mint a Zenodo DOI for this repo, as we are nearing submission.

We need to perform the following prior to DOI minting:

- [x] Review issues and determine if any are critical to resolve
- [x] Review READMEs to confirm a) clarity and b) that our results align with what we present in the paper (that they are all up to date and that they don't contradict)
- [x] Perform any software gardening to make sure repo is maximally reproducible

Thanks!

**Comment by jenna-tomkinson** [comment]
This issue is completed with PR #48, thanks!
