### ISSUE TITLE
Drop na columns in feature selection step

### ISSUE THREAD

**Issue by gwaybio** [WayScience/CFReT_data#9]
I am fitting UMAPs but cannot because there are missing values in the data frame. Please add `drop_na_columns` with an `na_cutoff=0` in [3.process-cfret-features](https://github.com/WayScience/CFReT_data/tree/main/3.process-cfret-features)

**Comment by gwaybio** [comment]
See https://github.com/cytomining/pycytominer/blob/master/pycytominer/feature_select.py for details

**Comment by jenna-tomkinson** [comment]
This issue was resolved in #10 so I will be closing this now.
